services:
  yana.database:
    image: mcr.microsoft.com/mssql/server
    container_name: yana.dev.database
    environment:
      - SA_PASSWORD=!YetAnotherNoteAppTestDb2025
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: