name: Build and test

on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/Yana.sln

      - name: Build
        run: dotnet build src/Yana.sln --no-restore

      - name: Test
        run: dotnet test src/Yana.sln --no-build --verbosity normal
